"""add inference_logs table

Revision ID: e32d6bd73b4f
Revises: 5d5ff132c56e
Create Date: 2026-08-01 16:19:15.801526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32d6bd73b4f'
down_revision: Union[str, Sequence[str], None] = '5d5ff132c56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('call_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('input_messages', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_inference_logs_conversation_id_created_at', 'inference_logs', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_inference_logs_created_at', 'inference_logs', ['created_at'], unique=False)
    op.create_index('ix_inference_logs_request_id', 'inference_logs', ['request_id'], unique=True)
    op.create_index('ix_inference_logs_status_created_at', 'inference_logs', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inference_logs_status_created_at', table_name='inference_logs')
    op.drop_index('ix_inference_logs_request_id', table_name='inference_logs')
    op.drop_index('ix_inference_logs_created_at', table_name='inference_logs')
    op.drop_index('ix_inference_logs_conversation_id_created_at', table_name='inference_logs')
    op.drop_table('inference_logs')
    # ### end Alembic commands ###
